# Generated by Django 5.2.6 on 2025-10-12 10:20

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(help_text='Username has to be under 64 characters.', max_length=64, unique=True, verbose_name='Username')),
                ('email', models.EmailField(help_text='Enter a valid email address', max_length=254, unique=True, verbose_name='Email')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('height', models.IntegerField(default=50, editable=False)),
                ('width', models.IntegerField(default=50, editable=False)),
                ('image', models.ImageField(default='default/default_profile.jpg', height_field='height', upload_to=users.models.get_image_url, verbose_name='Profile Image', width_field='width')),
                ('is_banned', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max 48 symbols.', max_length=48, verbose_name='Title')),
                ('height', models.IntegerField(default=50, editable=False)),
                ('width', models.IntegerField(default=50, editable=False)),
                ('image', models.ImageField(default='default/default_profile.jpg', height_field='height', upload_to=users.models.get_song_image_url, verbose_name='Song Image', width_field='width')),
                ('private', models.BooleanField(default=True, verbose_name='Privacy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='playlists',
            field=models.ManyToManyField(related_name='Playlists', to='users.playlist'),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max 48 symbols.', max_length=48, verbose_name='Title')),
                ('song', models.FileField(upload_to=users.models.get_song_url, validators=[users.models.validate_audio_file], verbose_name='Audio File')),
                ('height', models.IntegerField(default=50, editable=False)),
                ('width', models.IntegerField(default=50, editable=False)),
                ('image', models.ImageField(default='default/default_profile.jpg', height_field='height', upload_to=users.models.get_song_image_url, verbose_name='Song Image', width_field='width')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='Playlist', to='users.song'),
        ),
    ]
