# Generated by Django 5.2.7 on 2025-10-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='private',
            field=models.BooleanField(default=True, verbose_name='Private'),
        ),
    ]
