# Generated by Django 5.2.6 on 2025-10-02 10:26

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_id_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='song',
            name='height',
            field=models.IntegerField(default=50, editable=False),
        ),
        migrations.AddField(
            model_name='song',
            name='width',
            field=models.IntegerField(default=50, editable=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(default='default/default_profile.jpg', height_field='height', upload_to=users.models.get_song_image_url, verbose_name='Song Image', width_field='width'),
        ),
    ]
