# Generated by Django 5.2.6 on 2025-10-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_song_created_at_song_height_song_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
    ]
