# Generated by Django 5.2.6 on 2025-10-02 16:35

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_song_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max 48 symbols.', max_length=48, verbose_name='Title')),
                ('height', models.IntegerField(default=50, editable=False)),
                ('width', models.IntegerField(default=50, editable=False)),
                ('image', models.ImageField(default='default/default_profile.jpg', height_field='height', upload_to=users.models.get_song_image_url, verbose_name='Song Image', width_field='width')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(related_name='Playlist', to='users.song')),
            ],
        ),
    ]
