# Generated by Django 5.2.6 on 2025-10-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='playlists',
            field=models.ManyToManyField(related_name='Playlists', to='users.playlist'),
        ),
    ]
