# Generated by Django 5.2.6 on 2025-10-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_playlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='private',
            field=models.BooleanField(default=True, verbose_name='Privacy'),
        ),
    ]
